### ISSUE TITLE
Gatsby plugin error 

### ISSUE THREAD

**Issue by shakythesherpa** [developmentseed/aep#49]
Running into the following error when i try to run the command yarn serve to host the project locally
I am using Mac- OSx 10.15.7

> Error: 'babel-plugin-styled-components' is not installed which is needed by pl
  ugin 'gatsby-plugin-styled-components'

<img width="564" alt="Screen Shot 2021-04-07 at 11 54 55 PM" src="https://user-images.githubusercontent.com/731717/113966269-c7870700-97fc-11eb-8429-205f84aad3af.png">

**Comment by danielfdsilva** [comment]
@shakythesherpa Thank you for reporting this. This should be fixed now, you only need to run the project again.
