### ISSUE TITLE
pushing new branch to remote

### ISSUE THREAD

**Issue by akorkovelos** [developmentseed/aep#62]
Hi team, I have introduced a new case study, I have validated locally and everything seems to be working fine (locally). However, when I am trying to push the new branch to the remote I reveive an authentication error `fatal: Authentication failed for 'https://github.com/developmentseed/aep.git/'`. I assume this is a security issue that can be resolved via an access token or by simply being added as collaborator? Or is this something I should configure on my machine. Thanks!

**Comment by olafveerman** [comment]
Hi @akorkovelos.
Great to hear that everything is working locally. Just added you as a contributor to this repo with write access. You should be able to push a new branch.

Feel free to reopen this issue if the problem persists.
